// Code generated by ogen, DO NOT EDIT.

package ogenapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ProductGetOperation  OperationName = "ProductGet"
	ProductPostOperation OperationName = "ProductPost"
)
